// Alien race table: look, homeworld biomes, temperament, favourite goods, language syllables,
// building style, ship hull and walking speed. Lore lines are keyed by race id.
const race = (o) => ({ speed: 1.2, joiner: ' ', ...o });

export const RACES = [
  race({ id: 'vorran', name: 'Kaum Vorran', height: [2.4, 3.0], hue: [0.55, 0.75], glow: 0x9fd8ff,
    biomes: ['desert', 'barren', 'crystal', 'glass'], temperament: 'Tenang, bijak, dan penuh teka-teki',
    syllables: ['vor', 'ra', 'esh', 'tha', 'ul', 'ka', 'ren', 'iss', 'oth', 'ae'], joiner: '',
    wants: ['Silika', 'Emas', 'Kristal Anomali', 'Indium', 'Frost Crystal'], gifts: 'Kristal Alien',
    building: 'spire', ship: 'shard', speed: 1.1 }),
  race({ id: 'ksirr', name: 'Ksirr', height: [1.4, 1.9], hue: [0.05, 0.2], glow: 0xffd24a,
    biomes: ['toxic', 'fungal', 'swamp', 'lush'], temperament: 'Sibuk, cerewet, pedagang ulung',
    syllables: ['ksi', 'rr', 'tik', 'zz', 'kra', 'chi', 'xi', 'trk', 'ik'], joiner: "'",
    wants: ['Karbon', 'Protein Fauna', 'Fungal Mould', 'Ammonia', 'Belerang'], gifts: 'Nanit',
    building: 'hive', ship: 'insect', speed: 2.1 }),
  race({ id: 'blubo', name: 'Blubo', height: [1.2, 1.6], hue: [0.4, 0.95], glow: 0x7dffe0,
    biomes: ['ocean', 'exotic', 'candy', 'lush'], temperament: 'Ceria, penasaran, suka bercanda',
    syllables: ['blu', 'bo', 'plo', 'wub', 'oo', 'mlo', 'bub', 'lu', 'pi'], joiner: '-',
    wants: ['Oksigen', 'Garam', 'Natrium', 'Karang Nautilon', 'Klorin'], gifts: 'Nanit',
    building: 'bubble', ship: 'pod', speed: 0.9 }),
  race({ id: 'mekanid', name: 'Mekanid', height: [1.8, 2.3], hue: [0.0, 1.0], glow: 0xff5a3a,
    biomes: ['irradiated', 'volcanic', 'barren', 'frozen'], temperament: 'Logis, dingin, sangat teliti',
    syllables: ['zet', 'kor', 'bip', 'tron', 'ek', 'vek', 'dak', 'nul', 'ix'], joiner: '.',
    wants: ['Ferit', 'Kobalt', 'Tembaga', 'Uranium', 'Logam Penjaga'], gifts: 'Artefak Kuno',
    building: 'tech', ship: 'saucer', speed: 1.4 }),
  race({ id: 'aquor', name: 'Aquor', height: [1.5, 2.0], hue: [0.3, 0.55], glow: 0xc07dff,
    biomes: ['swamp', 'ocean', 'lush', 'frozen'], temperament: 'Ramah, gemar bernyanyi',
    syllables: ['aq', 'lu', 'rhee', 'mo', 'ssa', 'wo', 'ee', 'qua', 'nai'],
    wants: ['Oksigen', 'Karbon', 'Es Air', 'Garam', 'Protein Fauna'], gifts: 'Kristal Alien',
    building: 'reed', ship: 'manta', speed: 1.3 }),
  race({ id: 'kristalin', name: 'Kristalin', height: [1.9, 2.5], hue: [0.5, 0.62], glow: 0x8ff4ff,
    biomes: ['crystal', 'frozen', 'glass', 'exotic'], temperament: 'Berkilau, sabar, berbicara dalam nada',
    syllables: ['kri', 'zha', 'lin', 'ith', 'tae', 'vel', 'sii', 'qa', 'ren'], joiner: '',
    wants: ['Frost Crystal', 'Kristal Anomali', 'Serpih Kristal', 'Silika', 'Indium'], gifts: 'Kristal Alien',
    building: 'crystal', ship: 'prism', speed: 1.0 }),
  race({ id: 'mikoni', name: 'Mikoni', height: [1.1, 1.6], hue: [0.0, 0.1], glow: 0xd6ff7a,
    biomes: ['fungal', 'toxic', 'swamp', 'lush'], temperament: 'Pemalu, lembut, suka berkumpul',
    syllables: ['mu', 'ko', 'pip', 'shro', 'ni', 'po', 'lum', 'ba', 'ook'], joiner: '-',
    wants: ['Spora', 'Fungal Mould', 'Jamur Liar', 'Spora Ungu', 'Karbon'], gifts: 'Nanit',
    building: 'shroom', ship: 'spore', speed: 1.0 }),
  race({ id: 'aveli', name: 'Aveli', height: [1.7, 2.2], hue: [0.04, 0.14], glow: 0xfff08a,
    biomes: ['desert', 'lush', 'barren', 'candy'], temperament: 'Bangga, gesit, pencerita ulung',
    syllables: ['kee', 'ar', 'vi', 'ri', 'sha', 'tee', 'li', 'cha', 'aw'], joiner: "'",
    wants: ['Bulu Sayap', 'Biji Aneh', 'Buah Hutan', 'Emas', 'Mutiara'], gifts: 'Artefak Kuno',
    building: 'nest', ship: 'wing', speed: 1.6 }),
  race({ id: 'batugar', name: 'Batugar', height: [2.6, 3.3], hue: [0.05, 0.12], glow: 0xff8a2a,
    biomes: ['volcanic', 'barren', 'glass', 'desert'], temperament: 'Lamban, sabar, tak pernah ingkar janji',
    syllables: ['grom', 'bat', 'ur', 'dhu', 'gar', 'ok', 'rum', 'tor', 'ba'],
    wants: ['Obsidian', 'Belerang', 'Magnetized Ferrite', 'Batu Apung', 'Ferit'], gifts: 'Artefak Kuno',
    building: 'monolith', ship: 'rock', speed: 0.8 }),
  race({ id: 'rimbuna', name: 'Rimbuna', height: [2.8, 3.6], hue: [0.22, 0.36], glow: 0xb8ff6a,
    biomes: ['lush', 'swamp', 'fungal', 'ocean'], temperament: 'Teduh, bijak, berpikir sangat lama',
    syllables: ['rim', 'bu', 'oa', 'hel', 'dro', 'wen', 'ul', 'aa', 'mor'],
    wants: ['Karbon', 'Oksigen', 'Nektar', 'Gel Hayati', 'Es Air'], gifts: 'Kristal Alien',
    building: 'grove', ship: 'seed', speed: 0.7 }),
  race({ id: 'tintari', name: 'Tintari', height: [1.6, 2.1], hue: [0.8, 0.95], glow: 0xff7ae0,
    biomes: ['ocean', 'exotic', 'swamp', 'crystal'], temperament: 'Penasaran, licin, gemar menawar',
    syllables: ['tin', 'ta', 'ri', 'qlo', 'shu', 'ul', 'ee', 'mi', 'vo'], joiner: '-',
    wants: ['Garam', 'Klorin', 'Karang Nautilon', 'Mutiara', 'Kerang'], gifts: 'Nanit',
    building: 'shell', ship: 'squid', speed: 1.1 }),
  race({ id: 'kribo', name: 'Kribo', height: [1.5, 1.9], hue: [0.08, 0.16], glow: 0x7affc8,
    biomes: ['barren', 'desert', 'frozen', 'irradiated'], temperament: 'Cerdik, berisik, gemar mengutak-atik',
    syllables: ['kri', 'bo', 'tak', 'tik', 'pim', 'zap', 'nok', 'dip', 'gru'], joiner: '-',
    wants: ['Tembaga', 'Kobalt', 'Nikel', 'Logam Penjaga', 'Pirit'], gifts: 'Nanit',
    building: 'workshop', ship: 'junk', speed: 1.5 }),
  race({ id: 'lumari', name: 'Lumari', height: [2.8, 3.4], hue: [0.55, 0.72], glow: 0xb49bff,
    biomes: ['crystal', 'exotic', 'frozen', 'irradiated'], temperament: 'Sunyi, misterius, bicara lewat cahaya',
    syllables: ['lu', 'ma', 'ae', 'ri', 'sha', 'oon', 'el', 'ii', 'vey'], joiner: '',
    wants: ['Kristal Anomali', 'Cahaya Cair', 'Inti Bintang', 'Serpih Isotop', 'Tritium'], gifts: 'Kristal Alien',
    building: 'obelisk', ship: 'ring', speed: 0.9 }),
  race({ id: 'saurak', name: 'Saurak', height: [1.9, 2.4], hue: [0.25, 0.42], glow: 0xffb23a,
    biomes: ['desert', 'swamp', 'volcanic', 'lush'], temperament: 'Licik, tangguh, pedagang paling ulet',
    syllables: ['sss', 'ra', 'kh', 'zar', 'ith', 'ak', 'sha', 'gra', 'ul'], joiner: "'",
    wants: ['Kulit Ular', 'Sisik', 'Emas', 'Telur Fauna', 'Platinum'], gifts: 'Nanit',
    building: 'bazaar', ship: 'barge', speed: 1.4 }),
  race({ id: 'wolla', name: 'Wolla', height: [1.8, 2.3], hue: [0.05, 0.11], glow: 0x9fe0ff,
    biomes: ['frozen', 'barren', 'desert', 'lush'], temperament: 'Hangat, suka berkelana, pencinta musik',
    syllables: ['wo', 'la', 'mm', 'hu', 'bo', 'ra', 'nu', 'fu', 'ah'],
    wants: ['Bulu Lembut', 'Protein Fauna', 'Susu Fauna', 'Kayu Asing', 'Es Murni'], gifts: 'Artefak Kuno',
    building: 'yurt', ship: 'caravan', speed: 1.2 }),
  race({ id: 'nexar', name: 'Nexar', height: [1.8, 2.2], hue: [0.9, 1.0], glow: 0x3affff,
    biomes: ['irradiated', 'glass', 'barren', 'exotic'], temperament: 'Efisien, perhitungan, selalu menawar',
    syllables: ['nex', 'ar', 'vo', 'zi', 'kal', 'syn', 'ro', 'dex', 'tu'], joiner: '.',
    wants: ['Uranium', 'Platinum', 'Indium', 'Logam Penjaga', 'Kromatik'], gifts: 'Kristal Alien',
    building: 'tower', ship: 'freighter', speed: 1.3 }),
];

export const LORE = {
  vorran: ['Menara kami menyimpan suara leluhur.', 'Kristal bernyanyi saat dua bulan sejajar.'],
  ksirr: ['Sarang kami punya seribu lorong dan satu ratu.', 'Semua bisa ditukar, bahkan mimpi.'],
  blubo: ['Kami lahir dari hujan hangat di laut ungu.', 'Cahaya di perut kami berarti bahagia!'],
  mekanid: ['Inti kami ditempa di bintang yang telah mati.', 'Efisiensi adalah bentuk tertinggi keramahan.'],
  aquor: ['Nyanyian kami memanggil ikan dari laut dalam.', 'Sirip kami berubah warna saat jatuh cinta.'],
  kristalin: ['Kami tumbuh selapis demi selapis, satu abad per sisi.', 'Retakan di tubuh kami adalah catatan sejarah.'],
  mikoni: ['Kami semua terhubung lewat akar di bawah tanah.', 'Spora kami menari saat hujan pertama turun.'],
  aveli: ['Bulu terbaik hanya dipakai saat festival angin.', 'Sarang tertinggi milik pencerita terbaik.'],
  batugar: ['Aku sudah berdiri di sini sejak gunung itu masih kecil.', 'Janji Batugar ditulis di batu, bukan di pasir.'],
  rimbuna: ['Satu kalimat kami butuh satu musim untuk diucapkan.', 'Akar kami ingat setiap langkah pengembara.'],
  tintari: ['Tinta kami berwarna sesuai suasana hati.', 'Harga pertama selalu hanya permulaan.'],
  kribo: ['Mesin jalanku kubuat sendiri dari rongsokan!', 'Kalau bisa dibongkar, pasti bisa diperbaiki.'],
  lumari: ['Kami adalah cahaya yang lupa cara padam.', 'Waktu mengalir lebih pelan di dekat kami.'],
  saurak: ['Sisik yang bagus lebih berharga dari emas. Hampir.', 'Tiga telur, tiga kontrak dagang. Itu tradisi.'],
  wolla: ['Rumah kami adalah jalan di antara bintang.', 'Bulu tebal, hati lebih tebal lagi.'],
  nexar: ['Separuh tubuhku kubeli dengan kredit. Separuh lagi warisan.', 'Setiap detik adalah transaksi.'],
};
